# Random Tensor

Why random tensors?

Random tensors are important becouse the way many neural networks learn is that they start with tensors full of random numbers and the adjust those Random numbers to better represent the data.

 start with random numbers -> look at the data -> update the random numbers ->Look at the data -> update random numbers
Torch random Tesnors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [2]:
import torch    
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 


In [3]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6162, 0.7051, 0.9130, 0.5010],
        [0.3103, 0.3200, 0.8644, 0.2490],
        [0.3179, 0.7776, 0.6729, 0.9124]])

In [4]:
random_image_size_tensor = torch.rand(3, 224, 224)#height , width , colour chnals(R<G<B))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [5]:
print(torch. __version__)

2.3.0+cu121


In [6]:
torch.cuda.is_available()

True

In [7]:
var1 = torch.FloatTensor([1.0,2.0,3.0]).cuda()
var1

tensor([1., 2., 3.], device='cuda:0')

In [8]:
var1.device

device(type='cuda', index=0)

### Zeros and Ones

In [9]:
#create a tensor of zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Create a tensor of Ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
ones.dtype

torch.float32

### Creating a range of tensors and Tensors-Like

In [13]:
# use torch.range
one_to_ten = torch.arange(1,11) 
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#using steps methods
one_to_hunderd = torch.arange(start = 1, end = 100, step = 5)
one_to_hunderd

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [15]:
#Creating tesnor Like
Ten_zeros = torch.zeros_like(one_to_ten) # same shape as one_to_ten
Ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes


In [16]:
# float 32 tensor 
float_32_1_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,) # defaults to None)
float_32_1_tensor 

tensor([3., 6., 9.])

In [17]:
float_32_1_tensor.dtype


torch.float32

In [18]:
# float 32 tensor 
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [19]:
float_32_tesnor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device = "cuda", # what device is your tensor on (none for cpu)
                               requires_grad=False) # whether or not to track gradients with this tensor opertaion(for now)
                               

float_32_tesnor

tensor([3., 6., 9.], device='cuda:0')

##### tensor dataype
**note:** tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning

**1.** tensor not right datatype

**2.** tesnor not right shape

**3.** tensor not on the right device

In [20]:
#how to change the datatype
float_16_tensor = float_32_tesnor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

##### link for the pytorch datatype documentation
https://pytorch.org/docs/stable/tensors.html

In [21]:
#what happens
float_16_tensor * float_32_tesnor

tensor([ 9., 36., 81.], device='cuda:0')

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32,
                             device ="cuda",
                             requires_grad = False)
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [23]:
float_32_tesnor*int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

##### Getting the information from tensor 

**1.** tensor not right datatype - to do go get datatype from a tensor, can use `tesnor.dtype`

**2.** tesnor not right shape - to get shape from a tensor, can use `tensor.shape`

**3.** tensor not on the right device - to get deivr from a tensor, can use `tensor.device`

In [24]:
#create a tensor 
some_tensor = torch.rand((3,4),dtype = torch.float32, device = "cuda", requires_grad = False)
some_tensor

tensor([[0.0085, 0.3379, 0.4553, 0.3545],
        [0.6365, 0.9805, 0.7229, 0.2882],
        [0.2838, 0.0837, 0.0935, 0.2146]], device='cuda:0')

In [25]:
#find out the details about some_tensor
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device of some_tensor: {some_tensor.device}")

Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cuda:0


In [26]:
#create a tensor1
some_tensor1 = torch.rand(3,4)
some_tensor1

tensor([[0.3513, 0.1120, 0.0430, 0.4027],
        [0.5767, 0.6161, 0.1562, 0.4928],
        [0.0225, 0.6770, 0.6833, 0.7172]])

In [27]:
#find out the details about some_tensor
print(f"Datatype of some_tensor: {some_tensor1.dtype}")
print(f"Shape of some_tensor: {some_tensor1.shape}")
print(f"Device of some_tensor: {some_tensor1.device}")

Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cpu


#### Manipulating Tensor (tensor operation)

Tensor opertations includes:

**1.** Addition

**2.** Subtration

**3.** Multiplication(element - wise)

**4.** Division 

**5.** Matrix multiplication

In [28]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [29]:
#multiplication tenor with 10
tensor*10

tensor([10, 20, 30])

In [30]:
#subtration 10
tensor -10

tensor([-9, -8, -7])

In [31]:
# Try out Pytorch in_built function
# torch.add
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matric multiplication

Tow main ways of performing multiplication in nerural network and deeplearning 

**1.** Element- wise multiplication

**2.** Matrix multiplication (dot product )

`There are tow main rules that performing matrix multiplication need to satisy:`

**1.** The `inner dimension` must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
* **note** @ represent dot product like matrix multiplication

**2.** The resulting matrix has the shape of `outer dimensions`
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [32]:
#Element Wise Multiplication
print( tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix multiplication 
torch.matmul(tensor,tensor) #dot product 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [34]:
# Matrix multiplication by hand
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

CPU times: total: 0 ns
Wall time: 0 ns
tensor(14)


In [35]:
%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [38]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6586, 0.6792],
        [0.3465, 0.2178]])